### PR TITLE
Mtg notes 20150724

### PR DESCRIPTION
**Pull request by mbjones**
Hi Arfon and Dan -- here's a snapshot copy of the etherpad notes from today's meeting, converted to Markdown. -- Matt

### CODE REVIEW

**Comment by danielskatz** [comment]
Thanks - can you write to everyone and tell them this has moved to Github, and that they can still suggest changes through pull requests?

**Comment by mbjones** [comment]
Done.  Thanks.  I'll try to remember to take the notes in markdown format next time so there's less translation.

**Comment by danielskatz** [comment]
Thank you - it's much appreciated

**Comment by arfon** [comment]
Wonderful, thanks @mbjones! :sparkles:

**Pull request merged**
