### PR TITLE
Front matter, Sections 3 to 5, Appendix: typo and notes.

### PR DESCRIPTION
**Pull request by sctchoi**
Perhaps the long caption of Table 2 can be mostly moved to Section 3 and be replaced with a shorter version there.

### CODE REVIEW

**Comment by sctchoi** [comment]
Section 4: typo: 
"Knepley at al." -> "Knepley et al."

Section 5: note:
on what software not to cite, 
"Do not cite standard office software (e.g. Word, Excel) or programming languages.  Provide references only for specialized software."---Source: \url{https://owl.english.purdue.edu/owl/resource/560/10/}. Likewise,  generally speaking, we should not cite general software for conducting library research (e.g., JSTOR Mobile App), writing research papers (e.g., \LaTeX), scientific presentations (e.g., Powerpoint) or communications (e.g. Skype).

**Comment by sctchoi** [comment]
Front matter and Appendix: Add non breaking spaces after initials. Add middle initial "T.~" for myself.

**Comment by danielskatz** [comment]
This is very difficult to merge - it looks like it was started from a version that was a number of changes ago.  If you haven't made many changes, can you redo this with from the current version so the merge will work automatically and so that it is clear what you are changing?

**Comment by sctchoi** [comment]
Ok

Sou-Cheng

**Comment by sctchoi** [comment]
Made another attempt by closing this pull request and creating a fresh 
new pull request.

**Pull request closed without merging**
