### PR TITLE
Added examples of current varied forms of software mentions

### PR DESCRIPTION
**Pull request by jameshowison**
I pulled some examples of how software is currently being mentioned from Howison and Bullard 2015. Hopefully that provides some additional background and motivation.  The table might be a bit much, or need some re-formatting.

### CODE REVIEW

**Comment by danielskatz** [comment]
thanks - will accept and then maybe trim/edit

**Comment by jameshowison** [comment]
Great. Definitely trim! And add other examples from other publications etc
(I checked the Myernik one, but that was data, no? Perhaps there's another
I was thinking about?)

**Comment by danielskatz** [comment]
Yes, that's the one I was thinking of - but it's both data and infrastructure, I think, so I thought it was relevant in how people cite non-paper things.

**Comment by danielskatz** [comment]
if you can add a cite to it easily, please do

**Pull request merged**
